server:
  port: 8080

spring:
  application:
    name: fxnow

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

  # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1시간 (ms)

  # MySQL 데이터소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fxnow?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: d4594283!
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

# CORS 설정
app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed-headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    max-age: 3600

# 한국은행 API 설정
bok:
  api:
    base-url: https://ecos.bok.or.kr/api
    key: 9O98FZKTJM4VKXR7JFUG
    stat-code: 731Y001
    timeout: 5s

logging:
  level:
    com.txnow: DEBUG
    org.springframework: INFO
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json